apiVersion: v1
kind: Pod
metadata:
    name: test
    namespace: kafka
spec:
  containers:
  - name: kafka
    image: solsson/kafka:latest
    command:
    - sh
    - -c
    - "exec tail -f /dev/null"


    =============================================================================================================
#kubectl apply -f test.yaml -n kafka
